### ISSUE TITLE
Minify javascript files

### ISSUE THREAD

**Issue by charwking** [charwking/gift-exchange-web#19]
The `external.js` file is 1.1 MB, and takes 13+ seconds to download. Let's see what kind of improvements we can get by minifying this. (Might as well minify all js files, right?)

Note that when working locally, we probably want an un-minified version most of the time, so that it's easier to track down bugs. And when we deploy, it may prove helpful to have source-maps.

**Comment by cwkingjr** [comment]
@charwking Do you have any problem with using Uglifyjs to do this?

**Comment by charwking** [comment]
Nope
